# Generated by Django 6.0.4 on 2026-04-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_post_views_count_post_knowledge_b_views_c_f337ef_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP Verification',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='ai_summary',
        ),
        migrations.AlterField(
            model_name='actuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
